const ordersData = [
    {
        "id": "500102800",
        "clientName": "Julieta Miranda",
        "productType": "catalog",
        "productId": "baranda-desmontable-clasica",
        "productName": "Baranda: Desmontable Clásica",
        "selectedFinish": "Blanca",
        "selectedMeasure": "80 x 45 cm",
        "description": "Espesor tirante: 2.5 cm\nAlto tirante: 11cm\nTirante + Colchón: 23cm aprox",
        "deliveryMethod": "retira",
        "dispatchInfo": null,
        "prepDaysMin": 10,
        "prepDaysMax": 15,
        "prepDays": 15,
        "paidStatus": "total",
        "paidAmount": 45000,
        "totalAmount": 45000,
        "status": "pendiente",
        "creationDate": "2026-08-07T03:32:26.284Z",
        "completedDate": "",
        "image": "img/barandas-para-cama/baranda-desmontable-clasica/1780289706066-imagen.webp",
        "startDate": "2026-08-10T13:00:00.000Z",
        "estimatedReadyDate": "2026-08-31T21:00:00.000Z"
    },
    {
        "id": "958545308",
        "clientName": "Roció Natalia León Sotelo",
        "productType": "catalog",
        "productId": "mensulas",
        "productName": "Ménsulas para estantes",
        "selectedFinish": "20 x 20 cm",
        "selectedMeasure": "6 Un.",
        "description": "",
        "deliveryMethod": "retira",
        "dispatchInfo": null,
        "prepDaysMin": 1,
        "prepDaysMax": 1,
        "prepDays": 1,
        "paidStatus": "total",
        "paidAmount": 14000,
        "totalAmount": 14000,
        "status": "pendiente",
        "creationDate": "2026-08-07T16:54:03.836Z",
        "completedDate": "",
        "image": "img/migrados/decoracion/mensulas/mensulas.webp",
        "startDate": "2026-08-07T03:00:00.000Z",
        "estimatedReadyDate": "2026-08-11T02:59:00.000Z"
    }
];
