const ordersData = [
    {
        "id": "500102800",
        "clientName": "Julieta Miranda",
        "productType": "catalog",
        "productId": "baranda-desmontable-clasica",
        "productName": "Baranda: Desmontable Clásica",
        "selectedFinish": "Blanca",
        "selectedMeasure": "80 x 45 cm",
        "description": "Espesor tirante: 2.5 cm\nAlto tirante: 11cm\nTirante + Colchón: 23cm aprox",
        "deliveryMethod": "retira",
        "dispatchInfo": null,
        "prepDaysMin": 10,
        "prepDaysMax": 15,
        "prepDays": 15,
        "paidStatus": "total",
        "paidAmount": 45000,
        "totalAmount": 45000,
        "status": "pendiente",
        "creationDate": "2026-08-07T03:32:26.284Z",
        "completedDate": "",
        "image": "img/barandas-para-cama/baranda-desmontable-clasica/1780289706066-imagen.webp",
        "startDate": "2026-08-10T13:00:00.000Z",
        "estimatedReadyDate": "2026-08-31T21:00:00.000Z"
    },
    {
        "id": "958545308",
        "clientName": "Roció Natalia León Sotelo",
        "productType": "catalog",
        "productId": "mensulas",
        "productName": "Ménsulas para estantes",
        "selectedFinish": "20 x 20 cm",
        "selectedMeasure": "6 Un.",
        "description": "",
        "deliveryMethod": "retira",
        "dispatchInfo": null,
        "prepDaysMin": 1,
        "prepDaysMax": 1,
        "prepDays": 1,
        "paidStatus": "total",
        "paidAmount": 14000,
        "totalAmount": 14000,
        "status": "pendiente",
        "creationDate": "2026-08-07T16:54:03.836Z",
        "completedDate": "",
        "image": "img/migrados/decoracion/mensulas/mensulas.webp",
        "startDate": "2026-08-07T03:00:00.000Z",
        "estimatedReadyDate": "2026-08-11T02:59:00.000Z"
    },
    {
        "id": "884179251",
        "clientName": "Patricia Andrea Tijera",
        "productType": "catalog",
        "productId": "baranda-desmontable-clasica",
        "productName": "Baranda: Desmontable Clásica",
        "selectedFinish": "",
        "selectedMeasure": "",
        "description": "Ajuste de Baranda: 100 x 50 cm\nA 4\nB 11\nC  35",
        "deliveryMethod": "retira",
        "dispatchInfo": null,
        "prepDaysMin": 1,
        "prepDaysMax": 1,
        "prepDays": 1,
        "extraDays": 0,
        "paidStatus": "total",
        "paidAmount": 26000,
        "totalAmount": 26000,
        "status": "pendiente",
        "creationDate": "2026-08-08T22:11:22.381Z",
        "completedDate": "",
        "image": "img/barandas-para-cama/baranda-desmontable-clasica/1782437453517-imagen.webp",
        "startDate": "2026-08-10T03:00:00.000Z",
        "estimatedReadyDate": "2026-08-12T02:59:00.000Z"
    },
    {
        "id": "756188198",
        "clientName": "Alejandra Vecina",
        "productType": "catalog",
        "productId": "Estantes-Cortes-Madera",
        "productName": "Cortes de madera",
        "selectedFinish": "Natural",
        "selectedMeasure": "Otras medidas",
        "description": "Alto: 165 cm\nAncho: 85 cm\nProfundidad: 30 cm",
        "deliveryMethod": "retira",
        "dispatchInfo": null,
        "prepDaysMin": 3,
        "prepDaysMax": 5,
        "prepDays": 5,
        "extraDays": 0,
        "paidStatus": "nada",
        "paidAmount": 0,
        "totalAmount": 96000,
        "status": "pendiente",
        "creationDate": "2026-08-08T22:24:57.167Z",
        "completedDate": "",
        "image": "img/migrados/decoracion/estantes/estantes.webp",
        "startDate": "2026-08-10T03:00:00.000Z",
        "estimatedReadyDate": "2026-08-18T02:59:00.000Z"
    }
];
